### ISSUE TITLE
Plugin Not Working with Grafana v10.0.x

### ISSUE THREAD

**Issue by ngaragliano-tc** [gabrielthomasjacobs/grafana-zendesk-plugin#12]
Gabriel,
I would like to use this plugin, but it appears there's a version match issue with v10 of Grafana. I have attempted to install the plugin on Versions 10.0.0 and the latest, 10.0.2. Under both instances, I see the message "**This plugin doesn't support your version of Grafana.**" at `https://grafana.local/connections/datasources/gabrielthomasjacobs-zendesk-datasource`

I see a similar error when adding the plugin via the `install_plugins` configuration option using the plugin name `gabrielthomasjacobs-zendesk-datasource`.

Seems to be a version/dependency mismatch? Please let me know if I can provide any additional information regarding this issue. 

Thank you.

**Comment by gabrielthomasjacobs** [comment]
Hi @ngaragliano-tc! Thanks for the heads up. I'm also seeing something odd when trying to use the release from Github. When I install from [Grafana's plugin listing](https://grafana.com/grafana/plugins/gabrielthomasjacobs-zendesk-datasource/?tab=installation) it seems to be working on 10.0.0. Can you confirm if that works for you?

I'll double check 10.0.2 and look into the issue with the Github release.

**Comment by ngaragliano-tc** [comment]
Gabriel,
I did more testing. Installing from the `grafana-cli` command does not work and returns the same error:
```c2a2d1fd9b44:/usr/share/grafana$ grafana cli plugins install gabrielthomasjacobs-zendesk-datasource
Error: ✗ Plugin isn't available for your version of Grafana (Grafana v10.0.0 linux-amd64)
```

I found a solution that _works_ but it's less than ideal. If I perform the manual install steps by extracting the .zip provided in this repo into the grafana plugins dir, the plugin works and I am able to add the datasource:
![image](https://github.com/gabrielthomasjacobs/grafana-zendesk-plugin/assets/41648438/4f02331e-2a67-403a-97b8-aa4c33371822)
But still shows the `This plugin doesn't support your version of Grafana.` error. 

Since I'm using Grafana in a docker container, installing manually via the ZIP adds overhead to the workflow, and is inconsistent with how we install other plugins. 

Is there anything I can do to assist you in troubleshooting the versioning issue to allow this plugin to be installed via the WebGUI or cli?

Thanks.

**Comment by gabrielthomasjacobs** [comment]
@ngaragliano-tc ok, thank you for double checking that. I've set up grafana with docker and attempted to load my plugin and I'm receiving the same error as you. I'll let you know once the fix is live.

**Comment by gabrielthomasjacobs** [comment]
I did find a temporary workaround, if you add the cli param:
`-e GF_INSTALL_PLUGINS=https://grafana.com/api/plugins/gabrielthomasjacobs-zendesk-datasource/versions/1.1.0/download;gabrielthomasjacobs-zendesk-datasource`

or in docker-compose:
```
environment:
  - GF_INSTALL_PLUGINS=https://grafana.com/api/plugins/gabrielthomasjacobs-zendesk-datasource/versions/1.1.0/download;gabrielthomasjacobs-zendesk-datasource
```

It'll fetch from that download zip on the Grafana site instead. The syntax for the flag is `${url};${plugin-name}`

**Comment by ngaragliano-tc** [comment]
Gabriel,

I was able to get the plugin installed with this workaround. I do still see the `This plugin doesn't support your version of Grafana.`, and will have an engineer test the datasource later. 

Thank you

**Comment by nivpercepto** [comment]
@gabrielthomasjacobs 

I'm not able to install this plugin on Grafana Cloud, receiving the below error:

**This plugin doesn't support your version of Grafana.**

Anything I can do to resolve this?

Thanks

**Comment by gabrielthomasjacobs** [comment]
Hello @nivpercepto I am attempting to fix this right now, new version is under review with the Grafana team. Hopefully, after I simplified the Grafana Version target, it'll just work... I'll let you know once it's updated.

**Comment by nivpercepto** [comment]
Thanks very much!

**Comment by gabrielthomasjacobs** [comment]
Hello @nivpercepto and @ngaragliano-tc, I believe this issue to be fixed, please let me know if it's resolved in your instances!

Btw: I included a new variable named "CumulativeStatusCount" when you fetch the tickets. The count starts at 0 and as it iterates through each ticket, it increments/decrements based on the status. This gives a relative "number open" at a given point in time that you can plot/compare against other datasets!

**Comment by nivpercepto** [comment]
Thanks @gabrielthomasjacobs 
How should I setup the user and password when using SSO to login to Zendesk? (I don't have a password for Zendesk)
