### ISSUE TITLE
id is invalid

### ISSUE THREAD

**Issue by Scifire** [gabrielthomasjacobs/grafana-zendesk-plugin#16]
Hello,
We´d like to try the data source but unfortunately as soon as we want to configure a panel or explore it we get the message "id is invalid".
The "Save & test" of the data source is successful.
Any hint what could be wrong?

**Comment by ExperticityIT** [comment]
I found that keeping the datasource name as "Zendesk Datasource Plugin" fixes this problem. I noticed in the logs it was trying to retrieve this datasource: "path=/api/datasources/undefined/resources/ticket_fields status=400" when I named it anything else.

**Comment by gabrielthomasjacobs** [comment]
@ExperticityIT and @Scifire Thank you for looking into this and the info! I just merged a change that fixes this problem, I'll comment here when it's live though.

**Comment by gabrielthomasjacobs** [comment]
[v1.1.2 is live](https://grafana.com/grafana/plugins/gabrielthomasjacobs-zendesk-datasource/)

Thanks again for the help narrowing down the issue and the patience for a fix!

**Comment by Scifire** [comment]
@gabrielthomasjacobs thanks for the fix and the update :) Going to test the new version on Monday

**Comment by Scifire** [comment]
Can confirm it´s working for us. Just had to make sure Browser cache etc is deleted after updating the plugin.
Thanks again :)
